### ISSUE TITLE
Online demo shows an error in acc hours report

### ISSUE THREAD

**Issue by jaragunde** [Igalia/phpreport#100]
[Trac import]
Reported by: jaragunde
Original date: Thursday, 05 August 2010 19:18

In the online demo go to users -> acc hours report, and press 'view'. The ajax request would return a HTTP error 500 (internal server error). Some error is happening in the PHP backend.

**Comment by jaragunde** [comment]
[Trac import]
Comment by: jaragunde
Original date: Tuesday, 10 August 2010 20:25

The error is caused by the following uncaught exception:

```
[Tue Aug 10 20:20:12 2010] [error] [client 192.168.10.13] PHP Fatal error:  Uncaught exception 'SQLQueryErrorException' with message:

ERROR:  42601: syntax error at or near "AND"
LINE 1: ...nit)/60.0 AS add_hours FROM task WHERE projectid= AND usrid=...
                                                             ^
LOCATION:  base_yyerror, scan.l:807

in /var/www/demophpreport/phpreport/model/dao/TaskDAO/PostgreSQLTaskDAO.php:500
Stack trace:
#0 /var/www/demophpreport/phpreport/model/facade/action/GetPendingHolidayHoursAction.php(175): PostgreSQLTaskDAO->getVacations(Object(UserVO), Object(DateTime), Object(DateTime))
#1 /var/www/demophpreport/phpreport/model/facade/action/Action.php(112): GetPendingHolidayHoursAction->doExecute()
#2 /var/www/demophpreport/phpreport/model/facade/UsersFacade.php(252): Action->execute()
#3 /var/www/demophpreport/phpreport/web/services/getPendingHolidayHoursService.php(99): UsersFacade::GetPendingHolidayHours(Object(DateTime), Object(DateTime))
#4 {main}
  thrown in /var/www/demophpreport/phpreport/model/dao/TaskDAO/PostgreSQLTaskDAO.php on line 500, referer: http://demophpreport.igalia.com/web/viewWorkingHoursResultsReport.php
```

**Comment by jaragunde** [comment]
[Trac import]
Comment by: jaragunde
Original date: Tuesday, 10 August 2010 20:41

Fixed by this commit:
```
commit 51b128f06c01d9f1a8b7f862df227b585be44234
Author: Jacobo Aragunde Pérez <jaragunde@igalia.com>
Date:   Tue Aug 10 22:38:50 2010 +0200

    [Bug #100] Fix bug checking the existance of VACATIONS_PROJECT before performing the query.

```
