### ISSUE TITLE
Error creating new user

### ISSUE THREAD

**Issue by jaragunde** [Igalia/phpreport#141]
[Trac import]
Reported by: jaragunde
Original date: Sunday, 13 March 2011 15:50

In a fresh !PhpReport install, after logging in as 'admin', I tried to create a new user called 'foobar', with the same password, and member of groups 'admin' and 'staff', but I got an error. This is the output of the error file:

```
[Sun Mar 13 15:46:54 2011] [error] [client 127.0.0.1] PHP Warning:  pg_query(): Query failed: ERROR:  23505: llave duplicada viola restricción de unicidad "pk_usr"
LOCATION:  _bt_check_unique, nbtinsert.c:298 in /var/www/phpreport-personal/phpreport/model/dao/UserDAO/PostgreSQLUserDAO.php on line 617, referer: http://phpreport-personal/web/viewUsers.php
[Sun Mar 13 15:46:54 2011] [error] [client 127.0.0.1] PHP Fatal error:  Uncaught exception 'SQLQueryErrorException' with message 'ERROR:  23505: llave duplicada viola restricción de unicidad "pk_usr"
LOCATION:  _bt_check_unique, nbtinsert.c:298' in /var/www/phpreport-personal/phpreport/model/dao/UserDAO/PostgreSQLUserDAO.php:622
Stack trace:
#0 /var/www/phpreport-personal/phpreport/model/facade/action/CreateUserAction.php(77): PostgreSQLUserDAO->create(Object(UserVO))
#1 /var/www/phpreport-personal/phpreport/model/facade/action/Action.php(112): CreateUserAction->doExecute()
#2 /var/www/phpreport-personal/phpreport/model/facade/UsersFacade.php(170): Action->execute()
#3 /var/www/phpreport-personal/phpreport/web/services/createUsersService.php(168): UsersFacade::CreateUser(Object(UserVO))
#4 {main}
  thrown in /var/www/phpreport-personal/phpreport/model/dao/UserDAO/PostgreSQLUserDAO.php on line 622, referer: http://phpreport-personal/web/viewUsers.php
```

**Comment by jaragunde** [comment]
[Trac import]
Comment by: jaragunde
Original date: Sunday, 13 March 2011 15:53

I could create the user directly in the DB with ```insert into usr(login, password) values('foobar', md5('foobar'));```, and after that I could go to the user management screen and assign the groups properly.

**Comment by jaragunde** [comment]
[Trac import]
Comment by: jaragunde
Original date: Thursday, 19 May 2011 19:54

This bug should be fixed for the 2.0 release, because not being able to create new users makes this application useless.

**Comment by jaragunde** [comment]
[Trac import]
Comment by: jaragunde
Original date: Saturday, 09 July 2011 11:16

I've found the cause: the first two users you try to create after a fresh install fail, but the third one is created correctly. That's because the sequence which assigns ids to users as they are created starts with 0, but the file ```initialData.sql``` has already created users with ids 0 and 1. The first two trials to create a user from the application use ids 0 and 1 and fail, the successive ones don't.

**Comment by jaragunde** [comment]
[Trac import]
Comment by: jaragunde
Original date: Saturday, 09 July 2011 11:34

The problem can be fixed adding two calls to ```SELECT nextval(...)``` in ```initialData.sql``` to get the two first values of the sequence, so we prevent re-using the first two elements of the sequence. Also I have noticed that the same problem happens with the table ```user_group```, so the same measure must be taken.

**Comment by jaragunde** [comment]
[Trac import]
Comment by: jaragunde
Original date: Saturday, 09 July 2011 11:37

```
commit d34b2ddb4e7f0d0ab91961b6baab7f330b4f0c10
Author: Jacobo Aragunde Pérez <jaragunde@igalia.com>
Date:   Sat Jul 9 11:35:12 2011 +0200

    [Bug #141] Add calls to SELECT nextval(...) in initialData.sql so we skip the firs
```
