### ISSUE TITLE
Update task service should not require the date field

### ISSUE THREAD

**Issue by jaragunde** [Igalia/phpreport#487]
The service at `web/services/updateTasksService.php` requires entries to have a date field, even if it's not going to be updated.

The reason is it needs to check if the date is locked for edition or not. This is the error logged if you try it:
```
[12-Feb-2021 10:30:39 UTC] PHP Fatal error:  Uncaught TypeError: Argument 1 passed to PostgreSQLConfigDAO::isWriteAllowedForDate() must be an instance of DateTime, null given, called in /var/www/html/phpreport/model/facade/action/PartialUpdateTasksAction.php on line 85 and defined in /var/www/html/phpreport/model/dao/ConfigDAO/PostgreSQLConfigDAO.php:76
Stack trace:
#0 /var/www/html/phpreport/model/facade/action/PartialUpdateTasksAction.php(85): PostgreSQLConfigDAO->isWriteAllowedForDate(NULL)
#1 /var/www/html/phpreport/model/facade/action/Action.php(112): PartialUpdateTasksAction->doExecute()
#2 /var/www/html/phpreport/model/facade/TasksFacade.php(210): Action->execute()
#3 /var/www/html/phpreport/web/services/updateTasksService.php(272): TasksFacade::PartialUpdateReports(Array)
#4 {main}
  thrown in /var/www/html/phpreport/model/dao/ConfigDAO/PostgreSQLConfigDAO.php on line 76
```

This could be hiding another bug: what if we try to update a task which original date is locked, but the updated task is not?

**Comment by jaragunde** [comment]
Reviewed in PR #499:
```
commit 2e9e9b74272bb299d0b03f3c93c5a6e8ab3f8ae9
Merge: fdceece5 7c840201
Author: Jacobo Aragunde Pérez <jaragunde@igalia.com>
Date:   Tue Sep 14 11:27:33 2021 +0200

    [#487][#491] Improve locked date management in task updates
    
    Merge pull request #499 from Igalia/i491-enforce-locked-dates

commit 7c8402017fc1c6722ba320a355cd037bd0399c83
Author: Jacobo Aragunde Pérez <jaragunde@igalia.com>
Date:   Fri May 7 14:24:22 2021 +0200

    [#487] Break date assumption in checkOverlappingWithDBTasks.
    
    Ensure that date field is extracted from the saved task in case the
    DirtyTaskVO does not contain it.
    
    Also use array_key_first() to get the first task in the list, because
    a list of tasks where some were discarded might not start with 0. PHP
    version in the requirements has been bumped to 7.3.0 due to this.

commit d89345838e491df63109913a36f75d61039ee237
Author: Jacobo Aragunde Pérez <jaragunde@igalia.com>
Date:   Mon May 3 15:27:46 2021 +0200

    [#487][#491] Check lock on saved date before updating a task.
    
    We were only checking the new task date in a task update operation,
    instead of also checking the saved date. As a result, it was
    possible to move a task from a locked date to an unlocked one, and
    then update any other field.
    
    As a side effect, we break the assumption in PartialUpdateTasksAction
    that every DirtyTask contains a date, which helps fixing #491.
