### ISSUE TITLE
Error 500 when creating task with invalid project ID

### ISSUE THREAD

**Issue by jaragunde** [Igalia/phpreport#495]
When creating a task with an invalid project ID (e.g. one that doesn't exist), instead of failing gracefully it will cause an internal server error and return HTTP status 500. This is the logged error:
```
[22-Apr-2021 16:03:07 UTC] PHP Warning:  pg_query(): Query failed: ERROR:  23503: insert or update on table &quot;task&quot; violates foreign key constraint &quot;makeup&quot;
DETAIL:  Key (projectid)=(4000) is not present in table &quot;project&quot;.
SCHEMA NAME:  public
TABLE NAME:  task
CONSTRAINT NAME:  makeup
LOCATION:  ri_ReportViolation, ri_triggers.c:2463 in /var/www/html/phpreport/model/dao/TaskDAO/PostgreSQLTaskDAO.php on line 931
[22-Apr-2021 16:03:07 UTC] PHP Fatal error:  Uncaught SQLQueryErrorException: ERROR:  23503: insert or update on table "task" violates foreign key constraint "makeup"
DETAIL:  Key (projectid)=(4000) is not present in table "project".
SCHEMA NAME:  public
TABLE NAME:  task
CONSTRAINT NAME:  makeup
LOCATION:  ri_ReportViolation, ri_triggers.c:2463 in /var/www/html/phpreport/model/dao/TaskDAO/PostgreSQLTaskDAO.php:936
Stack trace:
#0 /var/www/html/phpreport/model/dao/TaskDAO/PostgreSQLTaskDAO.php(954): PostgreSQLTaskDAO->create(Object(TaskVO))
#1 /var/www/html/phpreport/model/facade/action/CreateTasksAction.php(87): PostgreSQLTaskDAO->batchCreate(Array)
#2 /var/www/html/phpreport/model/facade/action/Action.php(112): CreateTasksAction->doExecute()
#3 /var/www/html/phpreport/model/facade/TasksFacade.php(97): Action->execute()
#4 /var/www/html/phpreport/web/services/createTasksService.php(230): TasksFacade::CreateReports(Array)
#5 {main}
  thrown in /var/www/html/phpreport/model/dao/TaskDAO/PostgreSQLTaskDAO.php on line 936
```

The backend should fail gracefully when trying to create tasks with incorrect data.

**Comment by jaragunde** [comment]
Fixed in PR #498:
```
commit 7c8f2beda9b2ffc8ec819e2eba5341c2ed97a051
Merge: 81ed37a9 349c88f2
Author: Jacobo Aragunde Pérez <jaragunde@igalia.com>
Date:   Thu May 20 13:51:30 2021 +0200

    [#489][#495] Check project activation on task operations.
    
    Merge pull request #498 from Igalia/i489-inactive-project-tasks

commit fd7b2ab30cfc6c96a1b370317aaa509ee48cd860
Author: Jacobo Aragunde Pérez <jaragunde@igalia.com>
Date:   Thu Apr 22 18:12:25 2021 +0200

    [#489][#495] Check assigned project activation before creating a task.
    
    For every task we attempt to create, we check the activation field of
    the project it is assigned to.
    
    We collaterally fix #495 because we are checking for a null return
    value when fetching the project object.
