### ISSUE TITLE
Delete task service should not require the date field

### ISSUE THREAD

**Issue by jaragunde** [Igalia/phpreport#529]
Similarly to #487, when you try to delete a task via API and you don't send the date field, you will get an error. It shouldn't be necessary to send the date for this operation:
```
[18-Oct-2021 11:28:54 UTC] PHP Fatal error:  Uncaught TypeError: Argument 1 passed to PostgreSQLConfigDAO::isWriteAllowedForDate() must be an instance of DateTime, null given, called in /var/www/html/phpreport/model/facade/action/DeleteReportAction.php on line 76 and defined in /var/www/html/phpreport/model/dao/ConfigDAO/PostgreSQLConfigDAO.php:76
Stack trace:
#0 /var/www/html/phpreport/model/facade/action/DeleteReportAction.php(76): PostgreSQLConfigDAO->isWriteAllowedForDate(NULL)
#1 /var/www/html/phpreport/model/facade/action/Action.php(112): DeleteReportAction->doExecute()
#2 /var/www/html/phpreport/model/facade/TasksFacade.php(108): Action->execute()
#3 /var/www/html/phpreport/model/facade/TasksFacade.php(122): TasksFacade::DeleteReport(Object(TaskVO))
#4 /var/www/html/phpreport/web/services/deleteTasksService.php(131): TasksFacade::DeleteReports(Array)
#5 {main}
  thrown in /var/www/html/phpreport/model/dao/ConfigDAO/PostgreSQLConfigDAO.php on line 76
```

**Comment by dmtrek14** [comment]
We are in the process of rewriting the frontend for tasks. Any outstanding bugs and enhancements for the old interface will be taken into account as we implement the new design.
